### ISSUE TITLE
'container.volumes' is not recognized

### ISSUE THREAD

**Issue by linktimecloud** [InseeFrLab/marathon-to-kubernetes#11]
Copied a raw configuration from Marathon v1.10:
`
{
  "env": {
    "MINIO_ACCESS_KEY": "admin",
    "MINIO_SECRET_KEY": "123456"
  },
  "labels": {
    "HAPROXY_0_VHOST": "minio",
    "HAPROXY_GROUP": "admin"
  },
  "id": "/minio",
  "acceptedResourceRoles": [
    "*"
  ],
  "args": [
    "server",
    "/data"
  ],
  "backoffFactor": 1.15,
  "backoffSeconds": 1,
  "container": {
    "portMappings": [
      {
        "containerPort": 9000,
        "hostPort": 0,
        "labels": {
          "VIP_0": "/minio:9000"
        },
        "protocol": "tcp",
        "servicePort": 30592,
        "name": "http"
      }
    ],
    "type": "DOCKER",
    "volumes": [
      {
        "containerPath": "/data",
        "hostPath": "/opt/minio",
        "mode": "RW"
      }
    ],
    "docker": {
      "image": "minio/minio",
      "forcePullImage": false,
      "privileged": true,
      "parameters": []
    }
  },
  "cpus": 0.5,
  "disk": 0,
  "healthChecks": [
    {
      "gracePeriodSeconds": 300,
      "intervalSeconds": 60,
      "maxConsecutiveFailures": 3,
      "portIndex": 0,
      "timeoutSeconds": 20,
      "delaySeconds": 15,
      "protocol": "MESOS_HTTP",
      "path": "/minio/health/live",
      "ipProtocol": "IPv4"
    }
  ],
  "instances": 0,
  "maxLaunchDelaySeconds": 300,
  "mem": 1024,
  "gpus": 0,
  "networks": [
    {
      "mode": "container/bridge"
    }
  ],
  "requirePorts": false,
  "upgradeStrategy": {
    "maximumOverCapacity": 1,
    "minimumHealthCapacity": 1
  },
  "killSelection": "YOUNGEST_FIRST",
  "unreachableStrategy": {
    "inactiveAfterSeconds": 0,
    "expungeAfterSeconds": 0
  },
  "role": "slave_public",
  "fetch": [],
  "constraints": []
}
`

Exception was thrown:
`
2021-04-12 02:46:44.099 ERROR 1 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context
 with path [] threw exception [Request processing failed; nested exception is org.springframework.http.converter.HttpMessageConversionException: Type definit
ion error: [simple type, class mesosphere.marathon.client.model.v2.Volume]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException
: Cannot construct instance of 'mesosphere.marathon.client.model.v2.Volume' (no Creators, like default construct, exist): abstract types either need to be ma
pped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (PushbackInputStream); line: 35, column: 7] (through reference chain: mesosphere.marathon.client.model.v2.App["container"]->mesosphere.marathon.
client.model.v2.Container["volumes"]->java.util.ArrayList[0])] with root cause

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of 'mesosphere.marathon.client.model.v2.Volume' (no Creators, like d
efault construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (PushbackInputStream); line: 35, column: 7] (through reference chain: mesosphere.marathon.client.model.v2.App["container"]->mesosphere.marathon.
client.model.v2.Container["volumes"]->java.util.ArrayList[0])
`
Finally I changed container.volumes to an empty array, everything is OK. Is there something wrong with formatting 'container.volumes' ?

**Comment by olevitt** [comment]
Hi !

Thanks for your interest on this repository.
Sadly, this repository is no longer actively maintained.

If I had to guess :
The code depends heavily on the official marathon java library :  
```
<dependency>
			<groupId>com.mesosphere</groupId>
			<artifactId>marathon-client</artifactId>
			<version>0.6.2</version>
		</dependency>
```
Looks like you are hitting a bug linked to this library. The library looks like it's also no longer actively maintained. You may want to try the `0.6.3` version which has been released 1 year ago but I really don't know if it will fix this issue.

**Comment by linktimecloud** [comment]
> Hi !
> 
> Thanks for your interest on this repository.
> Sadly, this repository is no longer actively maintained.
> 
> If I had to guess :
> The code depends heavily on the official marathon java library :
> 
> ```
> <dependency>
> 			<groupId>com.mesosphere</groupId>
> 			<artifactId>marathon-client</artifactId>
> 			<version>0.6.2</version>
> 		</dependency>
> ```
> 
> Looks like you are hitting a bug linked to this library. The library looks like it's also no longer actively maintained. You may want to try the `0.6.3` version which has been released 1 year ago but I really don't know if it will fix this issue.

Thanks a lot @olevitt , sad this repo is inactive now :( , but anyway, I'll give it a try as you suggest
