### ISSUE TITLE
Add a license to the project

### ISSUE THREAD

**Issue by JoeAstin** [InseeFrLab/marathon-to-kubernetes#12]
I would be interested in using/extending this tool, but the lack of license prevents using it in any meaningful way. Is it possible to add an MIT style license (or some other license) to this project?

https://choosealicense.com/licenses/mit/#suggest-this-license

Thanks

**Comment by olevitt** [comment]
Hi !

Thanks for your interest on this project ! 
We will set the license to MIT just like most of our projects. I will do it (unless someone wants to open the PR) and it will probably be done by tomorrow.
